name: 'Check queries'
description: 'Check the queries that have been pushed'
author: 'GitHub <opensource+codeql-learninglab-actions@github.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'purple'